<?php
/**
 * FeeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\EbayFinanceApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eBay Finances API
 *
 * This API is used to retrieve seller payouts and monetary transaction details related to those payouts.
 *
 * The version of the OpenAPI document: v1.12.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\EbayFinanceApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FeeTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used to display fees that are automatically deducted from seller payouts.
 * @package     OpenAPI\EbayFinanceApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FeeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Fee"
     */
    public function testFee()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fee_jurisdiction"
     */
    public function testPropertyFeeJurisdiction()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fee_memo"
     */
    public function testPropertyFeeMemo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fee_type"
     */
    public function testPropertyFeeType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
