<?php
/**
 * ReferenceTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\EbayFinanceApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eBay Finances API
 *
 * This API is used to retrieve seller payouts and monetary transaction details related to those payouts.
 *
 * The version of the OpenAPI document: v1.12.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\EbayFinanceApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ReferenceTest Class Doc Comment
 *
 * @category    Class
 * @description This field is returned for NON_SALE_CHARGE transactions that contain non-transactional seller fees.
 * @package     OpenAPI\EbayFinanceApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ReferenceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Reference"
     */
    public function testReference()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reference_id"
     */
    public function testPropertyReferenceId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reference_type"
     */
    public function testPropertyReferenceType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
