<?php
/**
 * SellerFundsSummaryApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\EbayFinanceApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eBay Finances API
 *
 * This API is used to retrieve seller payouts and monetary transaction details related to those payouts.
 *
 * The version of the OpenAPI document: v1.12.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\EbayFinanceApiClient\Test\Api;

use \OpenAPI\EbayFinanceApiClient\Configuration;
use \OpenAPI\EbayFinanceApiClient\ApiException;
use \OpenAPI\EbayFinanceApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SellerFundsSummaryApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\EbayFinanceApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SellerFundsSummaryApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getSellerFundsSummary
     *
     * .
     *
     */
    public function testGetSellerFundsSummary()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
